CREATE TABLE ADDRESS(
    id IDENTITY PRIMARY KEY,
    address VARCHAR (50) NOT NULL,
    city VARCHAR (50) NOT NULL,
    state CHAR(2) NOT NULL,
    zip CHAR(5) NOT NULL,
    CHECK LENGTH(TRIM(address)) > 0,
    CHECK LENGTH(TRIM(city)) > 0,
    CHECK LENGTH(TRIM(state)) = 2,
    CHECK LENGTH(TRIM(zip)) = 5,
    UNIQUE (address, city, state, zip)
);

insert into ADDRESS (id, address, city, state, zip) values (1, '095 Cherokee Center', 'Washington', 'DC', '20392');
insert into ADDRESS (id, address, city, state, zip) values (2, '871 Butterfield Way', 'Washington', 'DC', '20319');
insert into ADDRESS (id, address, city, state, zip) values (3, '5 Oriole Plaza', 'Corpus Christi', 'TX', '78470');
insert into ADDRESS (id, address, city, state, zip) values (4, '56 Arizona Alley', 'Raleigh', 'NC', '27658');
insert into ADDRESS (id, address, city, state, zip) values (5, '4 Blaine Trail', 'Little Rock', 'AR', '72209');
insert into ADDRESS (id, address, city, state, zip) values (6, '65 Hayes Drive', 'San Diego', 'CA', '92196');
insert into ADDRESS (id, address, city, state, zip) values (7, '582 Ridge Oak Street', 'El Paso', 'TX', '79950');
insert into ADDRESS (id, address, city, state, zip) values (8, '21765 Sunnyside Pass', 'Morgantown', 'WV', '26505');
insert into ADDRESS (id, address, city, state, zip) values (9, '59383 Doe Crossing Road', 'Boca Raton', 'FL', '33487');
insert into ADDRESS (id, address, city, state, zip) values (10, '6721 Forest Center', 'Dallas', 'TX', '75221');
insert into ADDRESS (id, address, city, state, zip) values (11, '12 Waubesa Hill', 'Roanoke', 'VA', '24048');
insert into ADDRESS (id, address, city, state, zip) values (12, '4 Kipling Street', 'Pittsburgh', 'PA', '15235');
insert into ADDRESS (id, address, city, state, zip) values (13, '58 Clarendon Court', 'Fort Wayne', 'IN', '46862');
insert into ADDRESS (id, address, city, state, zip) values (14, '68956 Sycamore Junction', 'Dallas', 'TX', '75277');
insert into ADDRESS (id, address, city, state, zip) values (15, '8 Logan Center', 'New York City', 'NY', '10004');
insert into ADDRESS (id, address, city, state, zip) values (16, '9756 Stoughton Road', 'Sacramento', 'CA', '94237');
insert into ADDRESS (id, address, city, state, zip) values (17, '00819 Vernon Alley', 'Washington', 'DC', '20029');
insert into ADDRESS (id, address, city, state, zip) values (18, '82455 Myrtle Place', 'Tulsa', 'OK', '74103');
insert into ADDRESS (id, address, city, state, zip) values (19, '5740 Kim Place', 'Sacramento', 'CA', '94286');
insert into ADDRESS (id, address, city, state, zip) values (20, '1195 Summerview Trail', 'Des Moines', 'IA', '50981');
insert into ADDRESS (id, address, city, state, zip) values (21, '20 Caliangt Pass', 'Denver', 'CO', '80249');
insert into ADDRESS (id, address, city, state, zip) values (22, '36405 Aberg Pass', 'Wichita Falls', 'TX', '76310');
insert into ADDRESS (id, address, city, state, zip) values (23, '2 Porter Hill', 'Long Beach', 'CA', '90847');
insert into ADDRESS (id, address, city, state, zip) values (24, '49 Waywood Point', 'Fresno', 'CA', '93778');
insert into ADDRESS (id, address, city, state, zip) values (25, '31865 Glendale Lane', 'Des Moines', 'IA', '50315');
insert into ADDRESS (id, address, city, state, zip) values (26, '257 Amoth Crossing', 'Austin', 'TX', '78703');
insert into ADDRESS (id, address, city, state, zip) values (27, '80 Summer Ridge Place', 'Denver', 'CO', '80204');
insert into ADDRESS (id, address, city, state, zip) values (28, '4 Sugar Plaza', 'Los Angeles', 'CA', '90005');
insert into ADDRESS (id, address, city, state, zip) values (29, '0 Waywood Avenue', 'Minneapolis', 'MN', '55480');
insert into ADDRESS (id, address, city, state, zip) values (30, '187 Sugar Court', 'Seattle', 'WA', '98127');
insert into ADDRESS (id, address, city, state, zip) values (31, '8 Northridge Court', 'Oceanside', 'CA', '92056');
insert into ADDRESS (id, address, city, state, zip) values (32, '67 Eagan Crossing', 'Miami', 'FL', '33185');
insert into ADDRESS (id, address, city, state, zip) values (33, '345 Carioca Plaza', 'Honolulu', 'HI', '96815');
insert into ADDRESS (id, address, city, state, zip) values (34, '3456 Lien Pass', 'San Francisco', 'CA', '94142');
insert into ADDRESS (id, address, city, state, zip) values (35, '96 Forest Run Road', 'Syracuse', 'NY', '13205');
insert into ADDRESS (id, address, city, state, zip) values (36, '32076 Summer Ridge Court', 'Birmingham', 'AL', '35263');
insert into ADDRESS (id, address, city, state, zip) values (37, '6781 Scoville Way', 'Birmingham', 'AL', '35242');
insert into ADDRESS (id, address, city, state, zip) values (38, '92 Toban Trail', 'Jacksonville', 'FL', '32225');
insert into ADDRESS (id, address, city, state, zip) values (39, '6929 Pearson Place', 'Boca Raton', 'FL', '33487');
insert into ADDRESS (id, address, city, state, zip) values (40, '059 Marcy Plaza', 'Syracuse', 'NY', '13217');
insert into ADDRESS (id, address, city, state, zip) values (41, '8481 Dovetail Way', 'Houston', 'TX', '77065');
insert into ADDRESS (id, address, city, state, zip) values (42, '8 Fremont Street', 'Louisville', 'KY', '40280');
insert into ADDRESS (id, address, city, state, zip) values (43, '862 Fallview Avenue', 'Portland', 'OR', '97229');
insert into ADDRESS (id, address, city, state, zip) values (44, '655 Briar Crest Center', 'Charlotte', 'NC', '28210');
insert into ADDRESS (id, address, city, state, zip) values (45, '43125 Monterey Alley', 'Springfield', 'MA', '01114');
insert into ADDRESS (id, address, city, state, zip) values (46, '4 Village Junction', 'Pompano Beach', 'FL', '33069');
insert into ADDRESS (id, address, city, state, zip) values (47, '4573 Tony Drive', 'Spartanburg', 'SC', '29305');
insert into ADDRESS (id, address, city, state, zip) values (48, '4 Prentice Avenue', 'Santa Fe', 'NM', '87505');
insert into ADDRESS (id, address, city, state, zip) values (49, '22405 Eastwood Plaza', 'Salt Lake City', 'UT', '84170');
insert into ADDRESS (id, address, city, state, zip) values (50, '99 Vernon Circle', 'Louisville', 'KY', '40220');
insert into ADDRESS (id, address, city, state, zip) values (51, '8346 Lyons Trail', 'Louisville', 'KY', '40287');
insert into ADDRESS (id, address, city, state, zip) values (52, '25249 Dennis Street', 'El Paso', 'TX', '88563');
insert into ADDRESS (id, address, city, state, zip) values (53, '0 Sloan Hill', 'Sandy', 'UT', '84093');
insert into ADDRESS (id, address, city, state, zip) values (54, '18649 Nobel Drive', 'Metairie', 'LA', '70033');
insert into ADDRESS (id, address, city, state, zip) values (55, '509 Lotheville Pass', 'Chicago', 'IL', '60652');
insert into ADDRESS (id, address, city, state, zip) values (56, '42 Sloan Crossing', 'San Jose', 'CA', '95113');
insert into ADDRESS (id, address, city, state, zip) values (57, '7 Walton Trail', 'Jamaica', 'NY', '11499');
insert into ADDRESS (id, address, city, state, zip) values (58, '83073 Village Plaza', 'Green Bay', 'WI', '54313');
insert into ADDRESS (id, address, city, state, zip) values (59, '0463 Doe Crossing Drive', 'Hicksville', 'NY', '11854');
insert into ADDRESS (id, address, city, state, zip) values (60, '294 Clemons Trail', 'Bronx', 'NY', '10454');
insert into ADDRESS (id, address, city, state, zip) values (61, '4 Vidon Road', 'Milwaukee', 'WI', '53277');
insert into ADDRESS (id, address, city, state, zip) values (62, '1 Stang Alley', 'New York City', 'NY', '10045');
insert into ADDRESS (id, address, city, state, zip) values (63, '70330 Corben Point', 'Charleston', 'WV', '25356');
insert into ADDRESS (id, address, city, state, zip) values (64, '99 Artisan Hill', 'North Hollywood', 'CA', '91616');
insert into ADDRESS (id, address, city, state, zip) values (65, '1082 Lukken Plaza', 'Fairfax', 'VA', '22036');
insert into ADDRESS (id, address, city, state, zip) values (66, '84 Banding Terrace', 'Philadelphia', 'PA', '19196');
insert into ADDRESS (id, address, city, state, zip) values (67, '38015 Pierstorff Hill', 'Saint Louis', 'MO', '63131');
insert into ADDRESS (id, address, city, state, zip) values (68, '96 Jenifer Center', 'Honolulu', 'HI', '96820');
insert into ADDRESS (id, address, city, state, zip) values (69, '00958 Clarendon Junction', 'Louisville', 'KY', '40256');
insert into ADDRESS (id, address, city, state, zip) values (70, '39 Emmet Park', 'Melbourne', 'FL', '32941');
insert into ADDRESS (id, address, city, state, zip) values (71, '23152 Anthes Drive', 'Vancouver', 'WA', '98687');
insert into ADDRESS (id, address, city, state, zip) values (72, '84412 Hansons Center', 'Duluth', 'GA', '30096');
insert into ADDRESS (id, address, city, state, zip) values (73, '58788 Northport Terrace', 'Washington', 'DC', '20397');
insert into ADDRESS (id, address, city, state, zip) values (74, '01 Maryland Parkway', 'Oklahoma City', 'OK', '73197');
insert into ADDRESS (id, address, city, state, zip) values (75, '37 Northridge Crossing', 'Washington', 'DC', '20046');
insert into ADDRESS (id, address, city, state, zip) values (76, '192 Artisan Alley', 'Dallas', 'TX', '75367');
insert into ADDRESS (id, address, city, state, zip) values (77, '5957 Schlimgen Pass', 'Nashville', 'TN', '37250');
insert into ADDRESS (id, address, city, state, zip) values (78, '29 Sauthoff Crossing', 'New York City', 'NY', '10115');
insert into ADDRESS (id, address, city, state, zip) values (79, '7503 Algoma Street', 'Las Vegas', 'NV', '89166');
insert into ADDRESS (id, address, city, state, zip) values (80, '70394 Declaration Junction', 'Crawfordsville', 'IN', '47937');
insert into ADDRESS (id, address, city, state, zip) values (81, '47 Shopko Center', 'Jackson', 'TN', '38308');
insert into ADDRESS (id, address, city, state, zip) values (82, '19 Miller Hill', 'Richmond', 'VA', '23242');
insert into ADDRESS (id, address, city, state, zip) values (83, '0 Weeping Birch Street', 'Alexandria', 'LA', '71307');
insert into ADDRESS (id, address, city, state, zip) values (84, '9 Red Cloud Way', 'San Diego', 'CA', '92176');
insert into ADDRESS (id, address, city, state, zip) values (85, '4349 Erie Trail', 'Baltimore', 'MD', '21290');
insert into ADDRESS (id, address, city, state, zip) values (86, '65 Killdeer Trail', 'Philadelphia', 'PA', '19109');
insert into ADDRESS (id, address, city, state, zip) values (87, '43 Holmberg Lane', 'Macon', 'GA', '31210');
insert into ADDRESS (id, address, city, state, zip) values (88, '98 Warrior Crossing', 'Dallas', 'TX', '75210');
insert into ADDRESS (id, address, city, state, zip) values (89, '49 Corscot Plaza', 'Anaheim', 'CA', '92805');
insert into ADDRESS (id, address, city, state, zip) values (90, '9 Columbus Crossing', 'Mobile', 'AL', '36605');
insert into ADDRESS (id, address, city, state, zip) values (91, '6307 Tennessee Center', 'Columbus', 'OH', '43215');
insert into ADDRESS (id, address, city, state, zip) values (92, '694 Forest Run Way', 'Fort Worth', 'TX', '76121');
insert into ADDRESS (id, address, city, state, zip) values (93, '3919 Carberry Court', 'Miami', 'FL', '33283');
insert into ADDRESS (id, address, city, state, zip) values (94, '21190 Everett Junction', 'Sarasota', 'FL', '34238');
insert into ADDRESS (id, address, city, state, zip) values (95, '292 Ludington Center', 'Charlotte', 'NC', '28284');
insert into ADDRESS (id, address, city, state, zip) values (96, '37097 Annamark Parkway', 'Washington', 'DC', '20404');
insert into ADDRESS (id, address, city, state, zip) values (97, '7 Buena Vista Terrace', 'San Jose', 'CA', '95160');
insert into ADDRESS (id, address, city, state, zip) values (98, '5 Cascade Junction', 'Boston', 'MA', '02114');
insert into ADDRESS (id, address, city, state, zip) values (99, '66 Sheridan Road', 'Jackson', 'MS', '39216');
insert into ADDRESS (id, address, city, state, zip) values (100, '73 Goodland Plaza', 'Jeffersonville', 'IN', '47134');
insert into ADDRESS (id, address, city, state, zip) values (101, '60 Golden Leaf Circle', 'Hartford', 'CT', '06145');
insert into ADDRESS (id, address, city, state, zip) values (102, '57464 Reinke Crossing', 'Myrtle Beach', 'SC', '29579');
insert into ADDRESS (id, address, city, state, zip) values (103, '17 Maywood Street', 'Chicago', 'IL', '60636');
insert into ADDRESS (id, address, city, state, zip) values (104, '77 Miller Way', 'Dallas', 'TX', '75379');
insert into ADDRESS (id, address, city, state, zip) values (105, '338 Menomonie Center', 'Detroit', 'MI', '48206');
insert into ADDRESS (id, address, city, state, zip) values (106, '099 Hauk Junction', 'Newark', 'NJ', '07195');
insert into ADDRESS (id, address, city, state, zip) values (107, '711 Pond Street', 'Atlanta', 'GA', '31196');
insert into ADDRESS (id, address, city, state, zip) values (108, '8 Crescent Oaks Drive', 'Fort Worth', 'TX', '76192');
insert into ADDRESS (id, address, city, state, zip) values (109, '56290 Northwestern Parkway', 'Reading', 'PA', '19605');
insert into ADDRESS (id, address, city, state, zip) values (110, '173 Nelson Pass', 'Fayetteville', 'NC', '28305');
insert into ADDRESS (id, address, city, state, zip) values (111, '46 Aberg Hill', 'Madison', 'WI', '53790');
insert into ADDRESS (id, address, city, state, zip) values (112, '09 Northfield Parkway', 'Birmingham', 'AL', '35254');
insert into ADDRESS (id, address, city, state, zip) values (113, '23264 Ludington Center', 'Corpus Christi', 'TX', '78405');
insert into ADDRESS (id, address, city, state, zip) values (114, '361 Pankratz Drive', 'Springfield', 'IL', '62723');
insert into ADDRESS (id, address, city, state, zip) values (115, '66227 Annamark Street', 'Charlotte', 'NC', '28210');
insert into ADDRESS (id, address, city, state, zip) values (116, '04 Golf View Street', 'Des Moines', 'IA', '50362');
insert into ADDRESS (id, address, city, state, zip) values (117, '75 Kinsman Circle', 'Englewood', 'CO', '80150');
insert into ADDRESS (id, address, city, state, zip) values (118, '0242 Mccormick Junction', 'Ocala', 'FL', '34474');
insert into ADDRESS (id, address, city, state, zip) values (119, '62 Mesta Road', 'Torrance', 'CA', '90505');
insert into ADDRESS (id, address, city, state, zip) values (120, '2039 Park Meadow Drive', 'Jacksonville', 'FL', '32255');
insert into ADDRESS (id, address, city, state, zip) values (121, '91387 Aberg Place', 'Littleton', 'CO', '80127');
insert into ADDRESS (id, address, city, state, zip) values (122, '1 Mifflin Parkway', 'Shreveport', 'LA', '71151');
insert into ADDRESS (id, address, city, state, zip) values (123, '5 Spenser Lane', 'Pensacola', 'FL', '32575');
insert into ADDRESS (id, address, city, state, zip) values (124, '077 Declaration Avenue', 'Reno', 'NV', '89505');
insert into ADDRESS (id, address, city, state, zip) values (125, '7517 Dwight Court', 'Champaign', 'IL', '61825');
insert into ADDRESS (id, address, city, state, zip) values (126, '900 Corben Trail', 'Rochester', 'NY', '14639');
insert into ADDRESS (id, address, city, state, zip) values (127, '37316 Dwight Crossing', 'Houston', 'TX', '77260');
insert into ADDRESS (id, address, city, state, zip) values (128, '51 Kensington Terrace', 'Springfield', 'MA', '01129');
insert into ADDRESS (id, address, city, state, zip) values (129, '3 Hansons Lane', 'Marietta', 'GA', '30061');
insert into ADDRESS (id, address, city, state, zip) values (130, '939 Di Loreto Road', 'El Paso', 'TX', '79945');
insert into ADDRESS (id, address, city, state, zip) values (131, '850 Morningstar Junction', 'Rochester', 'NY', '14624');
insert into ADDRESS (id, address, city, state, zip) values (132, '2864 Schurz Junction', 'San Antonio', 'TX', '78235');
insert into ADDRESS (id, address, city, state, zip) values (133, '0020 Ludington Lane', 'Milwaukee', 'WI', '53210');
insert into ADDRESS (id, address, city, state, zip) values (134, '124 Warner Point', 'Newport Beach', 'CA', '92662');
insert into ADDRESS (id, address, city, state, zip) values (135, '90702 Bobwhite Junction', 'Salt Lake City', 'UT', '84115');
insert into ADDRESS (id, address, city, state, zip) values (136, '42250 Cordelia Trail', 'Jackson', 'MS', '39216');
insert into ADDRESS (id, address, city, state, zip) values (137, '46 Dwight Avenue', 'Atlanta', 'GA', '30392');
insert into ADDRESS (id, address, city, state, zip) values (138, '60 Anderson Parkway', 'Waco', 'TX', '76796');
insert into ADDRESS (id, address, city, state, zip) values (139, '408 Mariners Cove Court', 'Austin', 'TX', '78703');
insert into ADDRESS (id, address, city, state, zip) values (140, '8453 Hoffman Plaza', 'Naperville', 'IL', '60567');
insert into ADDRESS (id, address, city, state, zip) values (141, '57471 Cherokee Parkway', 'Honolulu', 'HI', '96815');
insert into ADDRESS (id, address, city, state, zip) values (142, '7 Troy Street', 'Houston', 'TX', '77218');
insert into ADDRESS (id, address, city, state, zip) values (143, '3836 Meadow Valley Trail', 'Sterling', 'VA', '20167');
insert into ADDRESS (id, address, city, state, zip) values (144, '6453 Vermont Court', 'Saint Louis', 'MO', '63110');
insert into ADDRESS (id, address, city, state, zip) values (145, '95 Troy Alley', 'Hamilton', 'OH', '45020');
insert into ADDRESS (id, address, city, state, zip) values (146, '19182 Cambridge Point', 'Honolulu', 'HI', '96810');
insert into ADDRESS (id, address, city, state, zip) values (147, '65 Bonner Terrace', 'Washington', 'DC', '20299');
insert into ADDRESS (id, address, city, state, zip) values (148, '0164 Hanover Circle', 'Metairie', 'LA', '70033');
insert into ADDRESS (id, address, city, state, zip) values (149, '6772 Waubesa Park', 'Albany', 'NY', '12242');
insert into ADDRESS (id, address, city, state, zip) values (150, '345 7th Park', 'Phoenix', 'AZ', '85083');
insert into ADDRESS (id, address, city, state, zip) values (151, '884 Delaware Parkway', 'Indianapolis', 'IN', '46202');
insert into ADDRESS (id, address, city, state, zip) values (152, '2882 Nevada Parkway', 'Grand Forks', 'ND', '58207');
insert into ADDRESS (id, address, city, state, zip) values (153, '0267 Di Loreto Court', 'Lansing', 'MI', '48912');
insert into ADDRESS (id, address, city, state, zip) values (154, '18 Harbort Trail', 'Harrisburg', 'PA', '17110');
insert into ADDRESS (id, address, city, state, zip) values (155, '6 Spenser Drive', 'Fresno', 'CA', '93778');
insert into ADDRESS (id, address, city, state, zip) values (156, '69575 Riverside Pass', 'Portland', 'OR', '97255');
insert into ADDRESS (id, address, city, state, zip) values (157, '5 Redwing Way', 'Seattle', 'WA', '98109');
insert into ADDRESS (id, address, city, state, zip) values (158, '93 Chinook Terrace', 'Oklahoma City', 'OK', '73114');
insert into ADDRESS (id, address, city, state, zip) values (159, '90 Vermont Lane', 'Greensboro', 'NC', '27455');
insert into ADDRESS (id, address, city, state, zip) values (160, '9662 Spohn Place', 'Omaha', 'NE', '68197');
insert into ADDRESS (id, address, city, state, zip) values (161, '4945 Monument Drive', 'Fort Myers', 'FL', '33906');
insert into ADDRESS (id, address, city, state, zip) values (162, '55 Manitowish Crossing', 'Silver Spring', 'MD', '20918');
insert into ADDRESS (id, address, city, state, zip) values (163, '85 Dorton Hill', 'Philadelphia', 'PA', '19141');
insert into ADDRESS (id, address, city, state, zip) values (164, '3775 Eggendart Hill', 'Santa Rosa', 'CA', '95405');
insert into ADDRESS (id, address, city, state, zip) values (165, '57 Bartelt Parkway', 'Milwaukee', 'WI', '53285');
insert into ADDRESS (id, address, city, state, zip) values (166, '2 Upham Hill', 'Portland', 'OR', '97229');
insert into ADDRESS (id, address, city, state, zip) values (167, '1108 Bluejay Drive', 'Toledo', 'OH', '43699');
insert into ADDRESS (id, address, city, state, zip) values (168, '1179 Hanson Terrace', 'Miami', 'FL', '33158');
insert into ADDRESS (id, address, city, state, zip) values (169, '1 Porter Plaza', 'Apache Junction', 'AZ', '85219');
insert into ADDRESS (id, address, city, state, zip) values (170, '7356 Dawn Lane', 'Fort Worth', 'TX', '76110');
insert into ADDRESS (id, address, city, state, zip) values (171, '1 Donald Parkway', 'Brooklyn', 'NY', '11236');
insert into ADDRESS (id, address, city, state, zip) values (172, '5 Mcbride Hill', 'Fort Lauderdale', 'FL', '33345');
insert into ADDRESS (id, address, city, state, zip) values (173, '386 Grasskamp Lane', 'Honolulu', 'HI', '96810');
insert into ADDRESS (id, address, city, state, zip) values (174, '3 Troy Place', 'Washington', 'DC', '20566');
insert into ADDRESS (id, address, city, state, zip) values (175, '8 Browning Road', 'Dallas', 'TX', '75246');
insert into ADDRESS (id, address, city, state, zip) values (176, '22 Browning Plaza', 'Gadsden', 'AL', '35905');
insert into ADDRESS (id, address, city, state, zip) values (177, '5250 Lawn Parkway', 'Washington', 'DC', '20337');
insert into ADDRESS (id, address, city, state, zip) values (178, '633 Bowman Trail', 'Decatur', 'GA', '30033');
insert into ADDRESS (id, address, city, state, zip) values (179, '577 Orin Circle', 'Abilene', 'TX', '79605');
insert into ADDRESS (id, address, city, state, zip) values (180, '0308 Commercial Plaza', 'Seminole', 'FL', '34642');
insert into ADDRESS (id, address, city, state, zip) values (181, '824 Butterfield Court', 'Louisville', 'KY', '40298');
insert into ADDRESS (id, address, city, state, zip) values (182, '509 Doe Crossing Point', 'El Paso', 'TX', '79994');
insert into ADDRESS (id, address, city, state, zip) values (183, '0 Arapahoe Crossing', 'New Orleans', 'LA', '70154');
insert into ADDRESS (id, address, city, state, zip) values (184, '949 Clemons Junction', 'Atlanta', 'GA', '30368');
insert into ADDRESS (id, address, city, state, zip) values (185, '73 Hoard Street', 'Boise', 'ID', '83705');
insert into ADDRESS (id, address, city, state, zip) values (186, '3069 Luster Plaza', 'Oklahoma City', 'OK', '73157');
insert into ADDRESS (id, address, city, state, zip) values (187, '92 American Place', 'Oakland', 'CA', '94616');
insert into ADDRESS (id, address, city, state, zip) values (188, '0310 Lakeland Pass', 'Reno', 'NV', '89505');
insert into ADDRESS (id, address, city, state, zip) values (189, '5 Towne Place', 'Sacramento', 'CA', '95823');
insert into ADDRESS (id, address, city, state, zip) values (190, '6 Tony Place', 'Charlotte', 'NC', '28225');
insert into ADDRESS (id, address, city, state, zip) values (191, '549 Steensland Terrace', 'Brockton', 'MA', '02305');
insert into ADDRESS (id, address, city, state, zip) values (192, '3 Ruskin Park', 'Arlington', 'TX', '76096');
insert into ADDRESS (id, address, city, state, zip) values (193, '0846 Vera Parkway', 'Pasadena', 'CA', '91109');
insert into ADDRESS (id, address, city, state, zip) values (194, '560 Talmadge Drive', 'El Paso', 'TX', '79905');
insert into ADDRESS (id, address, city, state, zip) values (195, '1 Shelley Avenue', 'Sacramento', 'CA', '94250');
insert into ADDRESS (id, address, city, state, zip) values (196, '36800 Brown Lane', 'Lexington', 'KY', '40515');
insert into ADDRESS (id, address, city, state, zip) values (197, '5 Milwaukee Plaza', 'Evanston', 'IL', '60208');
insert into ADDRESS (id, address, city, state, zip) values (198, '06571 Pennsylvania Street', 'Houston', 'TX', '77065');
insert into ADDRESS (id, address, city, state, zip) values (199, '79 Loomis Court', 'Seattle', 'WA', '98140');
insert into ADDRESS (id, address, city, state, zip) values (200, '5 Dayton Point', 'Laredo', 'TX', '78044');
